// 公共
export const SWITCH_SIDEBAR_COLLAPSE = 'SWITCH_SIDEBAR_COLLAPSE'
export const UPDATE_DOCUMENT_CLIENT_HEIGHT = 'UPDATE_DOCUMENT_CLIENT_HEIGHT'
export const UPDATE_MENU_NAV_LIST = 'UPDATE_MENU_NAV_LIST'
export const ADD_CONTENT_TAB = 'ADD_CONTENT_TAB'
export const UPDATE_CONTENT_TABS = 'UPDATE_CONTENT_TABS'
export const DELETE_CONTENT_TABS = 'DELETE_CONTENT_TABS'
export const UPDATE_CONTENT_TABS_ACTIVE_NAME = 'UPDATE_CONTENT_TABS_ACTIVE_NAME'
// 用户
export const UPDATE_USER_ID = 'UPDATE_USER_ID'
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
